name: exe201_lumos_mobile
description: "A Mobile App of Lumos"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  flutter_carousel_intro: ^1.0.3
  fan_carousel_image_slider: ^0.1.2
  pull_to_refresh_flutter3: ^2.0.2
  flutter_scrolling_fab_animated: ^0.1.4
  logger: ^2.0.2+1
  font_awesome_icon_class: ^0.0.6
  loading_animation_widget: ^1.2.0+4
  dot_navigation_bar: ^1.0.2
  google_fonts: ^4.0.4
  eva_icons_flutter: ^3.1.0
  ionicons: ^0.2.2
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.1.0
  animated_custom_dropdown: 3.0.0
  intl: ^0.18.1
  text_area: ^0.0.3
  group_radio_button: ^1.3.0
  flutter_rating_stars: ^1.0.3+4
  rich_readmore: ^1.1.1
  fdottedline_nullsafety: ^2.0.1
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  typethis: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_osm_plugin: ^0.70.4
  flutter_location_search: ^1.1.4
  flutter_image_slideshow: ^0.1.6
  cloud_firestore: ^4.15.8
  pretty_qr_code: ^3.2.1
  #  external_app_launcher: ^4.0.0
  url_launcher: ^6.0.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo3.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/
    - assets/font/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/font/Poppins-Black.otf
        - asset: assets/font/Poppins-BlackItalic.otf
        - asset: assets/font/Poppins-Bold.otf
        - asset: assets/font/Poppins-BoldItalic.otf
        - asset: assets/font/Poppins-ExtraBold.otf
        - asset: assets/font/Poppins-ExtraBoldItalic.otf
        - asset: assets/font/Poppins-ExtraLight.otf
        - asset: assets/font/Poppins-ExtraLightItalic.otf
        - asset: assets/font/Poppins-Italic.otf
        - asset: assets/font/Poppins-Light.otf
        - asset: assets/font/Poppins-LightItalic.otf
        - asset: assets/font/Poppins-Medium.otf
        - asset: assets/font/Poppins-MediumItalic.otf
        - asset: assets/font/Poppins-Regular.otf
        - asset: assets/font/Poppins-SemiBold.otf
        - asset: assets/font/Poppins-SemiBoldItalic.otf
        - asset: assets/font/Poppins-Thin.otf
        - asset: assets/font/Poppins-ThinItalic.otf
        - asset: assets/font/verdana.ttf
        - asset: assets/font/verdana-bold.ttf
        - asset: assets/font/verdana-bold-italic.ttf
          style: normal

    - family: LumosIcons #tên của bộ icons . Nhớ đặt đúng tên đã đặt như trên web nhé
      fonts:
        - asset: assets/font/LumosIcons.ttf #đường dẫn file .ttf

    - family: ZaloIcon #tên của bộ icons . Nhớ đặt đúng tên đã đặt như trên web nhé
      fonts:
        - asset: assets/font/ZaloIcon.ttf #đường dẫn file .ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
