/// Flutter icons ZaloIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZaloIcon
///      fonts:
///       - asset: fonts/ZaloIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ZaloIcon {
  ZaloIcon._();

  static const _kFontFam = 'ZaloIcon';
  static const String? _kFontPkg = null;

  static const IconData group_1000004349 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
